#!/usr/bin/env bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=34 blur_radius=30 color=0x40000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=4
  padding_right=4
  icon.font="Hack Nerd Font:Bold:15.0"
  label.font="Hack Nerd Font:Bold:13.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=3
  icon.padding_right=3
  label.padding_left=3
  label.padding_right=3
)
sketchybar --default "${default[@]}"

##### Adding AeroSpace Workspaces With App Icons #####
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  space=(
    icon="$sid"
    icon.padding_left=8
    icon.padding_right=4
    icon.shadow.color=0x80000000
    icon.shadow.distance=3
    label=""
    label.font="sketchybar-app-font:Regular:14.0"
    label.padding_left=0
    label.padding_right=8
    label.y_offset=-1
    label.shadow.color=0x80000000
    label.shadow.distance=3
    background.color=0x44ffffff
    background.border_color=0xaaffffff
    background.border_width=0
    background.corner_radius=8
    background.height=24
    background.drawing=on
    script="$PLUGIN_DIR/aerospace.sh $sid"
    click_script="aerospace workspace $sid"
  )
  sketchybar --add item space."$sid" left \
             --set space."$sid" "${space[@]}" \
             --subscribe space."$sid" aerospace_workspace_change
done

# Keep icons accurate when windows are opened, closed, or moved.
sketchybar --add item workspace_observer left \
           --set workspace_observer drawing=off update_freq=5 \
                                    script="$PLUGIN_DIR/update_workspace_icons.sh" \
           --subscribe workspace_observer front_app_switched system_woke

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \
           --add item meetingbar right \
           --set meetingbar drawing=off \
                            updates=on \
                            update_freq=30 \
                            icon=󰃭 \
                            script="$PLUGIN_DIR/meetingbar.sh" \
                            click_script="/usr/bin/shortcuts run 'SketchyBar MeetingBar Join' >/dev/null 2>&1"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
"$PLUGIN_DIR/update_workspace_icons.sh"
sketchybar --trigger aerospace_workspace_change \
           FOCUSED_WORKSPACE="$(aerospace list-workspaces --focused)"
